#! /bin/bash

init_camera_imx8mm()
{
	[ -d /sys/bus/platform/devices/32e30000.mipi-csi ] || return

	CAMERA=
	printf "Camera status: "

	if [ -d /sys/bus/i2c/drivers/ov5640/2-003c ]; then
		CAMERA="OV5640"
		FMT="UYVY8_1X16/1920x1080"
		CAMDEV="'ov5640 2-003c':0"
	elif [ -d /sys/bus/i2c/drivers/ap1302/2-003d ]; then
		CAMERA="AR0234"
		FMT="UYVY8_1X16/1920x1080"
		CAMDEV="'ap1302.2-003d':2"
	fi

	[ -n "$CAMERA" ] || { echo "Not found"; return; }

	# Configure media links and PADs
	media-ctl --reset
	media-ctl -l "$CAMDEV -> 'csis-32e30000.mipi-csi':0[1]"
	media-ctl -V "$CAMDEV [fmt:$FMT field:none]"
	media-ctl -V "'csis-32e30000.mipi-csi':0 [fmt:$FMT field:none]"
	media-ctl -V "'csi':0 [fmt:$FMT field:none]"

	echo "$CAMERA found"
}

init_camera_rk3568_cif()
{
	[[ -d /sys/bus/platform/devices/fe870000.phy ]] || return

	CAMERA=
	printf "Camera status: "

	if [ -d /sys/bus/i2c/drivers/ar0234/4-0018 ]; then
		CAMERA="AR0234"
		DEV="ar0234 4-0018"
		FMT="SGRBG8_1X8/1920x1200"
		SETFMT="width=1920,height=1200,pixelformat=GRBG"
	fi

	[ -n "$CAMERA" ] || { echo "Not found"; return; }

	media-ctl -d /dev/media0 --set-v4l2 "'$DEV':0 [fmt:$FMT field:none]"
	media-ctl -d /dev/media0 --set-v4l2 "'rkcif-mipi0':0 [fmt:$FMT field:none]"
	media-ctl -d /dev/media0 --set-v4l2 "'rkcif-mipi0':1 [fmt:$FMT field:none]"
	v4l2-ctl -d /dev/video1 --set-fmt-video=$SETFMT

	echo "$CAMERA found"
}

init_camera_rk3568_isp()
{
	[[ -d /sys/bus/platform/devices/fe870000.csi2-dphy-hw ]] || return

	CAMERA=
	printf "Camera status: "

	if [ -d /sys/bus/i2c/drivers/imx335/1-001a ]; then
		CAMERA="IMX335"
	elif [ -d /sys/bus/i2c/drivers/ar0234/4-0018 ]; then
		CAMERA="AR0234"
	elif [ -d /sys/bus/i2c/drivers/imx290/4-001a ]; then
		CAMERA="IMX327"
	elif [ -d /sys/bus/i2c/drivers/imx335/4-001a ]; then
		CAMERA="IMX335"
	elif [ -d /sys/bus/i2c/drivers/imx415/4-001a ]; then
		CAMERA="IMX415"
	elif [ -d /sys/bus/i2c/drivers/imx662/4-001a ]; then
		CAMERA="IMX662"
	elif [ -d /sys/bus/i2c/drivers/imx335/7-001a ]; then
		CAMERA="IMX335"
	elif [ -d /sys/bus/i2c/drivers/imx415/7-001a ]; then
		CAMERA="IMX415"
	fi

	[ -n "$CAMERA" ] || { echo "Not found"; return; }

	# Not need any special

	echo "$CAMERA found"
}

case "$1" in
start)
	init_camera_imx8mm
	init_camera_rk3568_cif
	init_camera_rk3568_isp

	;;
stop)

	;;
*)
	echo "Usage: $0 {start|stop}"

	;;
esac

exit 0
