#! /bin/bash

init_camera_imx()
{
	[ -d /sys/bus/platform/devices/32e30000.mipi-csi ] || return

	CAMERA=
	printf "Camera status: "

	if [ -d /sys/bus/i2c/drivers/ov5640/2-003c ]; then
		CAMERA=OV5640
		FMT="UYVY8_1X16/1920x1080"
		CAMDEV="'ov5640 2-003c':0"
	elif [ -d /sys/bus/i2c/drivers/ap1302/2-003d ]; then
		CAMERA=AR0234
		FMT="UYVY8_1X16/1920x1080"
		CAMDEV="'ap1302.2-003d':2"
	fi

	[ ! -z $CAMERA ] || { echo "Not found"; return; }

	# Configure media links and PADs
	media-ctl --reset
	media-ctl -l "$CAMDEV -> 'csis-32e30000.mipi-csi':0[1]"
	media-ctl -V "$CAMDEV [fmt:$FMT field:none]"
	media-ctl -V "'csis-32e30000.mipi-csi':0 [fmt:$FMT field:none]"
	media-ctl -V "'csi':0 [fmt:$FMT field:none]"

	echo "$CAMERA found"
}

init_camera_rockchip()
{
	[ -d /sys/bus/platform/devices/fe870000.csi2-dphy-hw ] || return

	CAMERA=
	printf "Camera status: "

	if [ -d /sys/bus/i2c/drivers/xc7160/4-001b ]; then
		CAMERA=XC7160
	elif [ -d /sys/bus/i2c/drivers/imx335/4-001a ]; then
		CAMERA=IMX335
	elif [ -d /sys/bus/i2c/drivers/imx415/4-001a ]; then
		CAMERA=IMX415
	elif [ -d /sys/bus/i2c/drivers/imx335/7-001a ]; then
		CAMERA=IMX335
	elif [ -d /sys/bus/i2c/drivers/imx415/7-001a ]; then
		CAMERA=IMX415
	elif [ -d /sys/bus/i2c/drivers/ar0233/10-0010 ]; then
		CAMERA=AR0233
	fi

	[ ! -z $CAMERA ] || { echo "Not found"; return; }

	FMT="SGRBG12_1X12/1920x1080"

	# Setup media format for DS90UB953 FPD-Link serializer
	if [ -d /sys/bus/i2c/drivers/ds90ub953/7-0018 ]; then
		media-ctl -V "'ds90ub953 7-0018':0 [fmt:$FMT field:none]"
	fi

	# Setup media format for DS90UB954 FPD-Link deserializer
	if [ -d /sys/bus/i2c/drivers/ds90ub960/7-0030 ]; then
		media-ctl -V "'ds90ub960 7-0030':0 [fmt:$FMT field:none]"
	fi

	# Not need any special

	echo "$CAMERA found"
}

case "$1" in
start)
	init_camera_imx
	init_camera_rockchip

	;;
stop)

	;;
*)
	echo "Usage: $0 {start|stop}"

	;;
esac

exit 0
