#! /bin/bash

case "$1" in
start|restart|reload)
	printf "Initializing sound: "

	for snddev in /dev/snd/controlC*; do
		[ -e "$snddev" ] || continue

		sndname=`basename $snddev`
		sndidx=${sndname#controlC}

		/usr/sbin/alsactl -I -D -U restore $sndidx || exit 1
	done

	echo "OK"

	;;
stop)

	;;
*)
	echo "Usage: $0 {start|stop|restart|reload}"

	;;
esac

exit 0
