#! /bin/bash

CONFIGFS=/sys/kernel/config

init_acm()
{
	mkdir -p functions/acm.1
	ln -sf functions/acm.1 configs/c.1
}

init_ms()
{
	mkdir -p functions/mass_storage.1
	echo "/dev/disk/by-label/rootfs" > functions/mass_storage.1/lun.0/file
	[ -f functions/mass_storage.1/stall ] || echo 0 > functions/mass_storage.1/stall
	echo 0 > functions/mass_storage.1/lun.0/cdrom
	echo 0 > functions/mass_storage.1/lun.0/nofua
	echo 1 > functions/mass_storage.1/lun.0/removable
	ln -sf functions/mass_storage.1 configs/c.1
}

init_rndis()
{
	mkdir -p functions/rndis.1
	echo "RNDIS" > functions/rndis.1/os_desc/interface.rndis/compatible_id
	echo "5162001" > functions/rndis.1/os_desc/interface.rndis/sub_compatible_id
	ln -sf functions/rndis.1 configs/c.1
}

init_uac2()
{
	mkdir -p functions/uac2.1
	echo 0x1 > functions/uac2.1/c_chmask
	echo 48000 > functions/uac2.1/c_srate
	echo 0xf > functions/uac2.1/p_chmask
	echo 48000 > functions/uac2.1/p_srate
	ln -sf functions/uac2.1 configs/c.1
}

init_gadget()
{
	[ -d /sys/class/udc/$1 ] || return 1

	# Create Gadget
	cd $CONFIGFS/usb_gadget
	mkdir -p g1
	cd g1

	# USB IDS
	echo 0x1d6b > idVendor	# Linux Foundation
	echo 0x0104 > idProduct	# Multifunction Composite Gadget

	# USB strings
	mkdir -p strings/0x409
	echo "Diasom" > strings/0x409/manufacturer
	cat /etc/machine-id > strings/0x409/serialnumber
	cat /proc/device-tree/model > strings/0x409/product

	# Create the configuration
	mkdir -p configs/c.1

	# Windows extensions to force config
	echo "1" > os_desc/use
	echo "0xcd" > os_desc/b_vendor_code
	echo "MSFT100" > os_desc/qw_sign
	ln -sf configs/c.1 os_desc

	# CDC ACM
	init_acm

	# Mass storage gadget
	init_ms

	# Microsoft "Remote NDIS" (RNDIS) Ethernet protocol
	#init_rndis

	# USB Audio Class 2 (UAC2)
	#init_uac2

	echo $1 > UDC

	return 0
}

stop_gadget()
{
	for GADGET in $CONFIGFS/usb_gadget/* ; do
		[ -f $GADGET/UDC ] || continue
		UDC=$(cat $GADGET/UDC)
		[ -z $UDC ] && continue
		echo "" > $GADGET/UDC
	done
}

[ -d $CONFIGFS ] || exit 0

case "$1" in
start)
	# i.NX8M
	init_gadget ci_hdrc.0 && echo "Gadget status: OK"

	# RK3568
	init_gadget fcc00000.usb && echo "Gadget status: OK"

	;;
stop)
	stop_gadget

	;;
*)
	echo "Usage: $0 {start|stop}"

	;;
esac

exit 0
