#! /bin/bash

init_framebuffer()
{
	printf "Framebuffer status: "

	FB0=/sys/class/graphics/fb0
	[ -d $FB0 ] || { echo "Not found"; return; }

	FBMODE=$FB0/mode
	MODE=$(cat $FBMODE 2&>/dev/null)
	[ -z $MODE ] || { echo "OK"; return; }

	FBMODES=$FB0/modes
	[ -f $FBMODES ] || { echo "Error"; return; }

	head -q -n 1 $FBMODES > $FBMODE

	echo "Initialized"
}

init_camera()
{
	[ -d /sys/bus/platform/devices/32e30000.mipi-csi ] || return

	CAMERA=
	printf "Camera status: "

	if [ -d /sys/bus/i2c/drivers/tevi-ap1302/2-003d ]; then
		CAMERA=AR0234
		#TODO: cfg
	fi

	[ ! -z $CAMERA ] || { echo "Not found"; return; }

	echo "$CAMERA found"
}

case "$1" in
start|restart|reload)
	init_framebuffer
	init_camera

	;;
stop)

	;;
*)
	echo "Usage: $0 {start|stop|restart|reload}"

	;;
esac

exit 0
